# Generated by Django 4.2.1 on 2023-05-14 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreer',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecalt', models.DateField(auto_now_add=True)),
                ('fecbaj', models.DateField(default=None, null=True)),
            ],
            options={
                'db_table': 'carrera',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descri', models.CharField(max_length=100)),
                ('nsesio', models.IntegerField()),
                ('durses', models.FloatField()),
                ('taller', models.IntegerField(default=None, null=True)),
                ('fecalt', models.DateField(auto_now_add=True)),
                ('fecbaj', models.DateField(default=None, null=True)),
                ('tipo', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'materia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=1)),
                ('fecalt', models.DateField(auto_now_add=True)),
                ('fecbaj', models.DateField(default=None, null=True)),
                ('area', models.CharField(default=None, max_length=50, null=True)),
                ('reqsim', models.IntegerField(default=None, null=True)),
                ('requi1', models.IntegerField(default=None, null=True)),
                ('requi2', models.IntegerField(default=None, null=True)),
                ('requi3', models.IntegerField(default=None, null=True)),
                ('requi4', models.IntegerField(default=None, null=True)),
                ('semest', models.IntegerField()),
                ('carreer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.carreer')),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
            ],
            options={
                'db_table': 'plan',
                'managed': True,
            },
        ),
    ]
